### ISSUE TITLE
Use GithubActions instead of Travis & AppVeyor

### ISSUE THREAD

**Issue by OskarStark** [symfony/maker-bundle#693]
### Todos

* [x] for `PHP-CS-Fixer` & `composer validate` #694
* [x] for tests (Linux) #701 
* [ ] for tests (Windows) - currently not possible #714
* [x] fix PHP 8 tests #715
* [x] deactivate Travis Webhook - @weaverryan

**Comment by OskarStark** [comment]
@weaverryan you can deactivate the travis webhook and close this issue.
We keep AppVeyor for now as mentioned in #714

**Comment by weaverryan** [comment]
Travis webhook deactivated - thanks @OskarStark!

**Comment by OskarStark** [comment]
🕺
